Add an aggregator CI job (#9)
As well as rename CI workflow back to .yaml, the issue was in the GH UI

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -16,6 +16,18 @@ env:
   RUST_BACKTRACE: short
 
 jobs:
+  success:
+    needs: [check, lint, test, format]
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: Fail if any dependency failed
+        run: |
+          if [ "${{ contains(needs.*.result, 'failure') }}" = "true" ]; then
+            echo "One or more jobs failed"
+            exit 1
+          fi
+
   check:
     runs-on: ubuntu-latest
     steps:
